const mongoose = require("mongoose"); // Import the Mongoose library, which is an Object Data Modeling (ODM) library for MongoDB and Node.js. It provides a straightforward way to model application data, including built-in type casting, validation, query building, and business logic hooks.

const orderSchema = new mongoose.Schema({ // Define a new Mongoose schema for the Order model. A schema is a blueprint that defines the structure of documents in a MongoDB collection, including the fields, their data types, and any validation rules or default values. The orderSchema variable will be used to create the Order model, which allows us to interact with the Order collection in the database.
    user : { type: mongoose.Schema.Types.ObjectId, ref: "User", required : true}, // Define a field named user in the orderSchema. The type of this field is ObjectId, which is a special type used to reference documents in other collections. The ref option specifies that this field references the User model, allowing us to establish a relationship between orders and users. The required option indicates that this field must have a value when creating or updating an order document.
    item : [{ // Define a field named item in the orderSchema. This field is an array of objects, where each object represents an item in the order. The square brackets [] indicate that this field can contain multiple items.
        productId : { type : mongoose.Schema.Types.ObjectId, ref: "Product", required : true }, // Define a field named productId in the item object. The type of this field is ObjectId, which is a special type used to reference documents in other collections. The ref option specifies that this field references the Product model, allowing us to establish a relationship between order items and products. The required option indicates that this field must have a value when creating or updating an order document.
        qty : { type : Number, required : true, min : 1 }, // Define a field named qty in the item object. The type of this field is Number, and it is marked as required, meaning that a value must be provided for this field when creating or updating an order document. The min option specifies that the minimum value for this field is 1, ensuring that the quantity of items in the order cannot be less than 1.
        price : { type : Number, required : true } // Define a field named price in the item object. The type of this field is Number, and it is marked as required, meaning that a value must be provided for this field when creating or updating an order document. This field represents the price of the individual item in the order.
    }],
    totalAmount : { type : Number, required : true}, // Define a field named totalAmount in the orderSchema. The type of this field is Number, and it is marked as required, meaning that a value must be provided for this field when creating or updating an order document. This field represents the total amount for the entire order, which is calculated based on the prices and quantities of the items in the order.
    address : {  // Define a field named address in the orderSchema. This field is an object that contains the details of the shipping address for the order. The address object includes several subfields, each representing a specific component of the address.
        fullname : { type : String, required : true }, // Define a subfield named fullname in the address object. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating an order document. This field represents the full name of the recipient for the order.
        street : { type : String, required : true}, // Define a subfield named street in the address object. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating an order document. This field represents the street address of the recipient for the order.
        postalCode : { type : String, required : true}, // Define a subfield named postalCode in the address object. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating an order document. This field represents the postal code of the recipient for the order.
        country : { type : String, required : true} // Define a subfield named country in the address object. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating an order document. This field represents the country of the recipient for the order.
    },
    paymentId : { type : String }, // Define a field named paymentId in the orderSchema. The type of this field is String, and it is not marked as required, meaning that a value may or may not be provided for this field when creating or updating an order document. This field represents the unique identifier for the payment transaction associated with the order, which can be used for tracking and reference purposes.
    status : { type : String, enum : ["pending", "shipped", "delivered"], default : "pending"} // Define a field named status in the orderSchema. The type of this field is String, and it is not marked as required, meaning that a value may or may not be provided for this field when creating or updating an order document. The enum option specifies that the value of this field must be one of the specified strings: "pending", "shipped", or "delivered". The default option sets the default value of this field to "pending" if no value is provided when creating a new order document. This field represents the current status of the order in the order processing workflow.
}, { timestamps : true }); // The second argument to the mongoose.Schema constructor is an options object. In this case, the timestamps option is set to true, which automatically adds createdAt and updatedAt fields to the orderSchema. These fields will store the timestamps for when the order document was created and last updated, respectively.


module.exports = mongoose.model("Order", orderSchema);