const mongoose = require("mongoose"); // Import the Mongoose library, which is an Object Data Modeling (ODM) library for MongoDB and Node.js. It provides a straightforward way to model application data, including built-in type casting, validation, query building, and business logic hooks.

const productSchema = new mongoose.Schema({ // Define a new Mongoose schema for the Product model. A schema is a blueprint that defines the structure of documents in a MongoDB collection, including the fields, their data types, and any validation rules or default values. The productSchema variable will be used to create the Product model, which allows us to interact with the Product collection in the database.
    name:{ type:String, required:true}, // Define a field named name in the productSchema. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating a product document. If a value is not provided for the name field, Mongoose will throw a validation error.
    description:{type:String, required:true}, // Define a field named description in the productSchema. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating a product document. If a value is not provided for the description field, Mongoose will throw a validation error.
    price:{type:Number, required:true}, // Define a field named price in the productSchema. The type of this field is Number, and it is marked as required, meaning that a value must be provided for this field when creating or updating a product document. If a value is not provided for the price field, Mongoose will throw a validation error.
    category:{type:String, required:true}, // Define a field named category in the productSchema. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating a product document. If a value is not provided for the category field, Mongoose will throw a validation error.
    stock:{type:Number, required:true}, // Define a field named stock in the productSchema. The type of this field is Number, and it is marked as required, meaning that a value must be provided for this field when creating or updating a product document. If a value is not provided for the stock field, Mongoose will throw a validation error.
    imageUrl:{type:String, required:true}, // Define a field named imageUrl in the productSchema. The type of this field is String, and it is marked as required, meaning that a value must be provided for this field when creating or updating a product document. If a value is not provided for the imageUrl field, Mongoose will throw a validation error.
    ratings:{type:Number, default:0}, // Define a field named ratings in the productSchema. The type of this field is Number, and it has a default value of 0.
    numReviews:{type:Number, default:0}, // Define a field named numReviews in the productSchema. The type of this field is Number, and it has a default value of 0.
    createdAt:{type:Date, default:Date.now} // Define a field named createdAt in the productSchema. The type of this field is Date, and it has a default value of the current date and time.
});

const Product = mongoose.model('Product', productSchema);
module.exports = Product;
